version: "3"

services:

  mariadb:
    image: mariadb:10.6
    restart: always
    mem_limit: 2g
    container_name: mariadbtest
    environment:
      MYSQL_ROOT_PASSWORD: 123TeSt321
      TERM: xterm
    #volumes:
    #  - ./volumes/var/lib/mysql:/var/lib/mysql
    #  - ./volumes/etc/mysql/conf.d:/etc/mysql/conf.d

    ports:
      - "3306:3306"

    # --skip-name-resolve
    # avoids: ""[Warning] IP address '172.17.0.60' could not be resolved: Name or service not known""
    command: mysqld --skip-name-resolve

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 10000:80
    environment:
      - PMA_ARBITRARY=1
